trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- deployment: VMDeploy
  displayName: 'Deploy to VM'
  environment: 
    name: 'VM'
    resourceName: 'VM'
    resourceType: 'virtualMachine'
  strategy:
    runOnce:
      deploy:   
        steps:
        - task: UseNode@1
          inputs:
            version: '16.x'
          displayName: 'Install Node.js'

        - script: |
            npm install
          displayName: 'npm install'

        - task: CopyFiles@2
          inputs:
            sourceFolder: '$(Build.SourcesDirectory)'
            contents: |
              src/*
              public/*
            targetFolder: '$(Build.ArtifactStagingDirectory)'
          displayName: 'Copy project files'

        - task: PublishPipelineArtifact@1
          inputs:
            artifactName: 'e2e-server'
            targetPath: '$(Build.ArtifactStagingDirectory)'
            publishLocation: 'pipeline'
          displayName: 'Publish npm artifact'

        - script: |
            npm run build
          displayName: 'npm build'
