trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- deployment: VM
  displayName: 'Deploy to VM'
  environment: 
    name: 'VM'
    resourceType: 'virtualMachine'
  strategy:
    runOnce:
      deploy:   
        steps:
        - script: |
            ls -R $(Build.SourcesDirectory)
          displayName: 'List contents of source directory'

        - task: CopyFiles@2
          inputs:
            sourceFolder: '$(Build.SourcesDirectory)'
            contents: |
              src/**
              public/**
              package.json
            targetFolder: '$(Build.ArtifactStagingDirectory)'
          displayName: 'Copy project files'          

        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
            includeRootFolder: true
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true
            
        - task: NodeTool@0
          inputs:
            versionSpec: '10.5'
          displayName: 'Install Node.js'

        - script: |
            npm install
            npm run build
          displayName: 'npm install and build'

        - task: PublishPipelineArtifact@1
          inputs:
            artifactName: 'drop'
            targetPath: '$(Build.ArtifactStagingDirectory)'
