trigger:
- main 

pool: 
  vmImage: 'ubuntu-latest'

steps:

- task: UseNode@1
  inputs:
    version: '16.17'

- task: Npm@1
  inputs:
    command: 'install'

- script: |
    ls -la $(Build.ArtifactStagingDirectory)
  displayName: 'List files in artifact staging directory'

- task: CopyFiles@2
  inputs: 
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
      **
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- script: |
    npm run build
  displayName: 'npm build'
  workingDirectory: $(Build.ArtifactStagingDirectory)

- task: PublishPipelineArtifact@1
  inputs: 
    artifactName: 'e2e-server'
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'